trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  paths:
    include:
    - '*'
    exclude:
    - '*.md'
    - /ActivityReservation.Clients/
    - /docs/

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tagName: 'standalone'
  imageName: '$(dockerId)/activityreservation:$(tagName)'

steps:

- script: dotnet build -c Release
  displayName: 'dotnet build'

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(imageName)
  displayName: 'Push docker image'