pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tagName: 'latest'
  imageName: '$(dockerId)/activityreservation:$(tagName)'

steps:

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(imageName)
  displayName: 'Push docker image'

- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: 'weihanli-vm'
    runOptions: inline

    inline: |
      kubectl set image deployment/activityreservation-deployment activityreservation=$(imageName)
