version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.6-alpine
    container_name: elasticsearch
    ports:
      - 9200:9200
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" #specific es java memory
      - "discovery.type=single-node"
    mem_limit: 512m # memory limit

  kibana:
    image: kibana:5.6
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  redis:
    container_name: redis
    image: redis:alpine
    ports: 
      - 6379:6379
    restart: always

  db:
    container_name: sqlserver
    image: microsoft/mssql-server-linux:2017-latest
    ports: 
      - 1433:1433
    environment: 
      - 'ACCEPT_EULA=Y'
      - 'MSSQL_SA_PASSWORD=Admin888'
    restart: always

  reservation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation
    ports:
      - 9080:80
    depends_on:
      - elasticsearch
      - redis
      - db
    links: 
      - elasticsearch:elasticsearch
      - redis:redis-server
      - db:db-server
